-- Migration: Add sub_sector column to complaints table
-- Date: 2025-10-31
-- Purpose: Store AI-generated sub-sector classification alongside main sector

-- Add sub_sector column
ALTER TABLE complaints
ADD COLUMN IF NOT EXISTS sub_sector VARCHAR(255);

-- Add index for faster filtering by sub_sector
CREATE INDEX IF NOT EXISTS idx_complaints_sub_sector ON complaints(sub_sector);

-- Add comment explaining the column
COMMENT ON COLUMN complaints.sub_sector IS 'Sub-sector classification (1 of 21) generated by AI from list_of_sectors.txt';
COMMENT ON COLUMN complaints.sector IS 'Main sector classification (1 of 10) generated by AI from list_of_sectors.txt';
