-- Migration: Create table for storing generated letters
-- Date: 2025-10-31
-- Purpose: Store letters generated by officers for complaints

CREATE TABLE IF NOT EXISTS generated_letters (
    id SERIAL PRIMARY KEY,
    complaint_id INTEGER REFERENCES complaints(id) ON DELETE CASCADE,
    letter_type VARCHAR(50) NOT NULL,
    letter_content TEXT NOT NULL,
    generated_by VARCHAR(100) NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_generated_letters_complaint ON generated_letters(complaint_id);
CREATE INDEX IF NOT EXISTS idx_generated_letters_type ON generated_letters(letter_type);
CREATE INDEX IF NOT EXISTS idx_generated_letters_date ON generated_letters(generated_at);

-- Comments
COMMENT ON TABLE generated_letters IS 'Generated official letters for complaints';
COMMENT ON COLUMN generated_letters.letter_type IS 'Type: notification, summon, closure, nfa, custom';
COMMENT ON COLUMN generated_letters.letter_content IS 'Full letter content in plain text or formatted';
COMMENT ON COLUMN generated_letters.generated_by IS 'Officer username/ID who generated the letter';
