#!/bin/bash
# Setup Nginx as HTTPS Reverse Proxy for SPRM Backend

echo "🔧 Setting up Nginx with SSL for SPRM Backend..."

# Install nginx and certbot
sudo apt update
sudo apt install -y nginx certbot python3-certbot-nginx

# Create nginx config for backend
sudo tee /etc/nginx/sites-available/sprm-backend << 'EOF'
server {
    listen 80;
    server_name api.sprm.mtailabs.ai;  # Change this to your backend domain

    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name api.sprm.mtailabs.ai;  # Change this to your backend domain

    # SSL certificates (will be auto-generated by certbot)
    ssl_certificate /etc/letsencrypt/live/api.sprm.mtailabs.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.sprm.mtailabs.ai/privkey.pem;

    # SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Proxy settings
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Increase timeout for long-running requests
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
    }

    # File upload size limit
    client_max_body_size 100M;
}
EOF

# Enable the site
sudo ln -sf /etc/nginx/sites-available/sprm-backend /etc/nginx/sites-enabled/

# Test nginx config
sudo nginx -t

echo "✅ Nginx configured!"
echo ""
echo "📝 Next steps:"
echo "1. Point your domain 'api.sprm.mtailabs.ai' to this server's IP"
echo "2. Run: sudo certbot --nginx -d api.sprm.mtailabs.ai"
echo "3. Restart nginx: sudo systemctl restart nginx"
echo "4. Update frontend to use: https://api.sprm.mtailabs.ai"
